// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgVWGqIkvgVNYbM-qgZw7CHBw2YM6KCNo',
    appId: '1:104143026082:web:4eb978b89495a1a2eaa4fb',
    messagingSenderId: '104143026082',
    projectId: 'sprinter-27ea3',
    authDomain: 'sprinter-27ea3.firebaseapp.com',
    databaseURL: 'https://sprinter-27ea3-default-rtdb.firebaseio.com',
    storageBucket: 'sprinter-27ea3.firebasestorage.app',
    measurementId: 'G-8MM89EBPCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBSls4TRhJHPwlMkwV5qIjxSA805py3nc',
    appId: '1:104143026082:android:770c258a7d8f2b67eaa4fb',
    messagingSenderId: '104143026082',
    projectId: 'sprinter-27ea3',
    databaseURL: 'https://sprinter-27ea3-default-rtdb.firebaseio.com',
    storageBucket: 'sprinter-27ea3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxe1QZ3T3I69uaqA8FOcUPDfQyaRS64dg',
    appId: '1:104143026082:ios:c9137f9ae3a0fe6deaa4fb',
    messagingSenderId: '104143026082',
    projectId: 'sprinter-27ea3',
    databaseURL: 'https://sprinter-27ea3-default-rtdb.firebaseio.com',
    storageBucket: 'sprinter-27ea3.firebasestorage.app',
    androidClientId: '104143026082-v1r3pusk57legr49uoj9ms6g51idbk45.apps.googleusercontent.com',
    iosClientId: '104143026082-euks8mbvs7ab4jsulvq9re9d9njvfocl.apps.googleusercontent.com',
    iosBundleId: '123',
  );
}
